export const query = graphql`
  query {
    posts: allMarkdownRemark(
      filter: {fields: {source: { eq: "pages" }, slug: { ne: null } } }
      sort: { fields: [fields___prefix], order: DESC }
    ){
      edges {
        node {
          excerpt(pruneLength: 250)
          fields {
            slug
            prefix
          }
        }
      }
    }
  }
`;