# From My-Files.jsx

export const query = graphql`
  query MyFilesQuery {
    site {
      siteMetadata {
        siteURL
      }
    }
    allFile {
      edges {
        node {
          sourceInstanceName
          relativePath
          publicURL
          internal {
            type
            description
          }
        }
      }
    }
  }
`
###############
# Output
###############
#{
#  "data": {
#    "site": {
#      "siteMetadata": {
#        "siteURL": "https://prp1277.github.io"
#      }
#    },
#    "allFile": {
#      "edges": [
#        {
#          "node": {
#            "sourceInstanceName": "img",
#            "relativePath": "First-file-delete.PNG",
#            "publicURL": "/static/First-file-delete-709d810df4b2e14418b0d88cc67b0ae9.PNG",
#            "internal": {
#              "type": "File",
#              "description": "File \"src\\img\\First-file-delete.PNG\""
#            }
#          }
#        },
#        {
#          "node": {
#            "sourceInstanceName": "img",
#            "relativePath": "StudyGuidesTweet.JPG",
#            "publicURL": "/static/StudyGuidesTweet-6993928d663e0e6cc67857c0cf1768ba.JPG",
#            "internal": {
#              "type": "File",
#              "description": "File \"src\\img\\StudyGuidesTweet.JPG\""
#            }
#          }
#        },
