query MyImagesQuery{
    allImageSharp{
    edges{
      node{
        original{
          src
        }
        sizes{
          originalName
          sizes
          aspectRatio
        }
      }
    }
  }
}

###############
# Output
###############
#{
#  "data": {
#    "allImageSharp": {
#      "edges": [
#        {
#          "node": {
#            "sizes": {
#              "originalName": "First-file-delete.PNG",
#              "sizes": "(max-width: 673px) 100vw, 673px",
#              "aspectRatio": 1.5157657657657657
#            }
#          }
#        },
#        {
#          "node": {
#            "sizes": {
#              "originalName": "StudyGuidesTweet.JPG",
#              "sizes": "(max-width: 800px) 100vw, 800px",
#              "aspectRatio": 1.5476575121163167
#            }
#          }
#        },